name: Soilcrete-web Build Latest Image

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  ORG_NAME: apipluspower
  IMAGE_TAG: ghcr.io/apipluspower/soilcrete:latest
  GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}

jobs:
  build-image:
    timeout-minutes: 10
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build Soilcrete-web
        run: |
          docker build -t ${IMAGE_TAG} .

      - name: Push Storefront Image
        if: ${{ github.event_name == 'push' }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ${REGISTRY} -u ${ORG_NAME} --password-stdin
          docker push ${IMAGE_TAG}