name: Build Image Soilcrete web

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  ORG_NAME: apipluspower
  IMAGE_TAG: ghcr.io/apipluspower/soilcrete-web:latest
  GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}

jobs:
  build-development-image:
    timeout-minutes: 10
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build Flutter Web
        run: |
          docker build -t ${IMAGE_TAG} .

      - name: Build And Push website Image
        if: ${{ github.event_name == 'push' }}
        run: |
          docker build -t ${IMAGE_TAG} .
          echo ${GITHUB_TOKEN} | docker login ${REGISTRY} -u ${ORG_NAME} --password-stdin
          docker push ${IMAGE_TAG}

